version: '2'
services:
  shinobi:
    image: migoller/shinobidocker:microservice-debian
    env_file:
      - MySQL.env
      - Shinobi.env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./config:/config
      - /mnt/media/shinobi/videos:/opt/shinobi/videos
      - /dev/shm/shinobiDockerTemp:/dev/shm/streams
    ports:
      - "8886:8080"
